package com.lingang.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lingang.bean.BannerLocal;
import com.lingang.bean.SearchHistory;
import com.lingang.bean.Student;

import com.lingang.greendao.BannerLocalDao;
import com.lingang.greendao.SearchHistoryDao;
import com.lingang.greendao.StudentDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bannerLocalDaoConfig;
    private final DaoConfig searchHistoryDaoConfig;
    private final DaoConfig studentDaoConfig;

    private final BannerLocalDao bannerLocalDao;
    private final SearchHistoryDao searchHistoryDao;
    private final StudentDao studentDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bannerLocalDaoConfig = daoConfigMap.get(BannerLocalDao.class).clone();
        bannerLocalDaoConfig.initIdentityScope(type);

        searchHistoryDaoConfig = daoConfigMap.get(SearchHistoryDao.class).clone();
        searchHistoryDaoConfig.initIdentityScope(type);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        bannerLocalDao = new BannerLocalDao(bannerLocalDaoConfig, this);
        searchHistoryDao = new SearchHistoryDao(searchHistoryDaoConfig, this);
        studentDao = new StudentDao(studentDaoConfig, this);

        registerDao(BannerLocal.class, bannerLocalDao);
        registerDao(SearchHistory.class, searchHistoryDao);
        registerDao(Student.class, studentDao);
    }
    
    public void clear() {
        bannerLocalDaoConfig.clearIdentityScope();
        searchHistoryDaoConfig.clearIdentityScope();
        studentDaoConfig.clearIdentityScope();
    }

    public BannerLocalDao getBannerLocalDao() {
        return bannerLocalDao;
    }

    public SearchHistoryDao getSearchHistoryDao() {
        return searchHistoryDao;
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

}
