package com.lingang.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.lingang.bean.BannerLocal;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BANNER_LOCAL".
*/
public class BannerLocalDao extends AbstractDao<BannerLocal, Long> {

    public static final String TABLENAME = "BANNER_LOCAL";

    /**
     * Properties of entity BannerLocal.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property NewsId = new Property(1, String.class, "newsId", false, "NEWS_ID");
        public final static Property NewsTitle = new Property(2, String.class, "newsTitle", false, "NEWS_TITLE");
        public final static Property ImgPath = new Property(3, String.class, "imgPath", false, "IMG_PATH");
        public final static Property LocalImgPath = new Property(4, String.class, "localImgPath", false, "LOCAL_IMG_PATH");
        public final static Property Names = new Property(5, String.class, "names", false, "NAMES");
    }


    public BannerLocalDao(DaoConfig config) {
        super(config);
    }
    
    public BannerLocalDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BANNER_LOCAL\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"NEWS_ID\" TEXT," + // 1: newsId
                "\"NEWS_TITLE\" TEXT," + // 2: newsTitle
                "\"IMG_PATH\" TEXT," + // 3: imgPath
                "\"LOCAL_IMG_PATH\" TEXT," + // 4: localImgPath
                "\"NAMES\" TEXT);"); // 5: names
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BANNER_LOCAL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BannerLocal entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String newsId = entity.getNewsId();
        if (newsId != null) {
            stmt.bindString(2, newsId);
        }
 
        String newsTitle = entity.getNewsTitle();
        if (newsTitle != null) {
            stmt.bindString(3, newsTitle);
        }
 
        String imgPath = entity.getImgPath();
        if (imgPath != null) {
            stmt.bindString(4, imgPath);
        }
 
        String localImgPath = entity.getLocalImgPath();
        if (localImgPath != null) {
            stmt.bindString(5, localImgPath);
        }
 
        String names = entity.getNames();
        if (names != null) {
            stmt.bindString(6, names);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BannerLocal entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String newsId = entity.getNewsId();
        if (newsId != null) {
            stmt.bindString(2, newsId);
        }
 
        String newsTitle = entity.getNewsTitle();
        if (newsTitle != null) {
            stmt.bindString(3, newsTitle);
        }
 
        String imgPath = entity.getImgPath();
        if (imgPath != null) {
            stmt.bindString(4, imgPath);
        }
 
        String localImgPath = entity.getLocalImgPath();
        if (localImgPath != null) {
            stmt.bindString(5, localImgPath);
        }
 
        String names = entity.getNames();
        if (names != null) {
            stmt.bindString(6, names);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public BannerLocal readEntity(Cursor cursor, int offset) {
        BannerLocal entity = new BannerLocal();
        readEntity(cursor, entity, offset);
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BannerLocal entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNewsId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setNewsTitle(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setImgPath(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setLocalImgPath(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setNames(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(BannerLocal entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(BannerLocal entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BannerLocal entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
